name: "build"

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

  schedule:
    - cron: '0 0 1 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build images
        run: |
          ./scripts/run_all.sh --build

      - name: Push images
        if: ${{ github.repository_owner == 'roc-streaming' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          ./scripts/run_all.sh --push
