name: "build"

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:

  schedule:
    - cron: '0 0 1 * *'

jobs:
  make-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build images
        run: |
          ./scripts/run_all.sh --build

      - name: Push images
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          ./scripts/run_all.sh --push
